- hosts: ansible-worker
  gather_facts: no

  tasks: 
    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
      become: yes
      tags: git_init

    - name: copy id_rsa и id_rsa.pub
      ansible.builtin.copy:
        src: ../ssh_keys/id_rsa
        dest: "~/.ssh/id_rsa"
        mode: '0600'
      become: yes
      tags: git_init

    - name: copy id_rsa и id_rsa.pub
      ansible.builtin.copy:
        src: "../ssh_keys/id_rsa.pub"
        dest: "~/.ssh/id_rsa.pub"
        mode: '0644'
      become: yes
      tags: git_init