  hosts: ansible-worker
  gather_facts: no

  tasks: 
      name: change data in index.html
      ansible.builtin.copy:
        src: ../files/index.html
        dest: /home/ansible-worker/www/stud-template/index.html
        mode: '0644'
      become: yes
      tags: build_repo